project_id = "ihyidluahpfyfsrxvgke"

[functions.bootstrap-admin]
verify_jwt = false

[functions.create-sales-rep]
verify_jwt = false

[functions.create-demo-merchant]
verify_jwt = false

[functions.fireblocks-transfer]
verify_jwt = false

[functions.plaid-link]
verify_jwt = false

[functions.plaid-transfer]
verify_jwt = false

[functions.process-fulfillment-queue]
verify_jwt = false